import { NextRequest } from 'next/server'
import { error, ok, rateLimit } from '@/lib/api-helpers'
import { createServiceSupabaseClient } from '@/lib/supabase-admin'
import { verifyNps } from '@/lib/nps-signature'
import { logger } from '@/lib/logger'

const MAX_COMENTARIO_LEN = 1000

/**
 * POST /api/public/nps-avaliar
 * Public — saves a NPS rating from client.
 * Body: { atendimentoId, sig, nota (1-5), comentario? }
 * Link must be HMAC-signed (generated by /api/nps/send).
 */
export async function POST(req: NextRequest) {
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0].trim() ?? 'unknown'
  if (!rateLimit(`nps-pub:${ip}`, 10, 60_000)) return error('Muitas tentativas', 429)

  try {
    const body = await req.json()
    const { atendimentoId, sig, nota, comentario } = body

    if (!atendimentoId) return error('atendimentoId é obrigatório', 400)
    if (!verifyNps(atendimentoId, sig)) return error('Link inválido ou expirado', 403)
    if (!nota || nota < 1 || nota > 5) return error('nota deve ser entre 1 e 5', 400)
    if (comentario && typeof comentario === 'string' && comentario.length > MAX_COMENTARIO_LEN) {
      return error(`comentario muito longo (máx ${MAX_COMENTARIO_LEN} caracteres)`, 400)
    }

    const supabase = createServiceSupabaseClient()

    // Fetch atendimento to get lava_jato_id + client info
    const { data: at } = await supabase
      .from('atendimentos')
      .select('lava_jato_id, cliente_nome, clientes(nome, telefone)')
      .eq('id', atendimentoId)
      .single()

    if (!at) return error('Atendimento não encontrado', 404)

    const clienteNome     = (at as any).clientes?.nome ?? at.cliente_nome ?? null
    const clienteTelefone = (at as any).clientes?.telefone ?? null

    // Check if already rated (avoid duplicates)
    const { data: existing } = await supabase
      .from('nps_avaliacoes')
      .select('id')
      .eq('atendimento_id', atendimentoId)
      .maybeSingle()

    if (existing) {
      return ok({ saved: true, alreadyRated: true })
    } else {
      await supabase
        .from('nps_avaliacoes')
        .insert({
          lava_jato_id:   at.lava_jato_id,
          atendimento_id: atendimentoId,
          cliente_nome:   clienteNome,
          telefone:       clienteTelefone,
          nota:           Number(nota),
          comentario:     comentario?.trim() || null,
        })
    }

    return ok({ saved: true })
  } catch (e: any) {
    logger.error('nps.avaliar.error', e)
    return error('Erro ao salvar avaliação', 500)
  }
}
